### ISSUE TITLE
GitHub Poderia Ter Conquistas e Recompensas , oque vocês acham ?

### ISSUE THREAD

**Issue by KaweMaximo** [ccuffs/ideias#10]
Eu gostaria muito que o github tivesse conquistas , planos e recompensas por commits e etc , seria um sonho conquistar tudo isso na plataforma.

**Comment by Dovyski** [comment]
Você não está sozinho nessa, @KaweMaximo , com certeza muitas pessoas (eu incluído) gostaria disso. Um plano de ter conquistas e recompensas por atividades no github (e disciplinas, projetos, etc) já está em andamento no curso.

O sistema de [intranet](https://cc.uffs.edu.br/intranet) foi um primeiro passo em relação a isso. Até fizemos uma movimentação de ideias durante o hacktoberfest 2020 na issue #8. Aos pouquinhos essa ideia está sendo colocada em prática 😄

**Comment by KaweMaximo** [comment]
> Você não está sozinho nessa, @KaweMaximo , com certeza muitas pessoas (eu incluído) gostaria disso. Um plano de ter conquistas e recompensas por atividades no github (e disciplinas, projetos, etc) já está em andamento no curso.
> 
> O sistema de [intranet](https://cc.uffs.edu.br/intranet) foi um primeiro passo em relação a isso. Até fizemos uma movimentação de ideias durante o hacktoberfest 2020 na issue #8. Aos pouquinhos essa ideia está sendo colocada em prática 😄 

 Caramba que massa , estou torcendo por essa ;)
